# Generated by Django 5.0.7 on 2024-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandesTraiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('nom_agent', models.CharField(max_length=100)),
                ('prenom_agent', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('type_de_vue', models.CharField(max_length=100)),
                ('A', models.IntegerField()),
                ('D', models.IntegerField()),
                ('S', models.IntegerField()),
                ('P', models.FloatField()),
            ],
            options={
                'ordering': ['-P'],
            },
        ),
    ]
