# Generated by Django 5.0.7 on 2024-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_demandestraiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('type_de_vue', models.CharField(max_length=100)),
                ('quota_value', models.IntegerField()),
            ],
            options={
                'ordering': ['ville', 'type_de_vue'],
                'unique_together': {('ville', 'type_de_vue')},
            },
        ),
    ]
