# Generated by Django 5.0.7 on 2024-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedDemandesRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('nom_agent', models.CharField(max_length=255)),
                ('prenom_agent', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255)),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('type_de_vue', models.CharField(max_length=255)),
                ('date_debut_retraite', models.DateField()),
                ('date_de_la_demande', models.DateField()),
            ],
            options={
                'verbose_name': 'Rejected Demande Retrait',
                'verbose_name_plural': 'Rejected Demandes Retraits',
            },
        ),
    ]
