# Generated by Django 5.0.7 on 2024-07-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rejecteddemandesretrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=255)),
                ('nom_agent', models.CharField(max_length=255)),
                ('prenom_agent', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=50)),
                ('cat_prof', models.CharField(max_length=50)),
                ('date_demande', models.DateField()),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('nombre_total_enfants', models.IntegerField()),
                ('nombre_accompagnateurs', models.IntegerField()),
                ('nombre_enfants_chambre_parents', models.IntegerField()),
                ('total_membres_famille', models.IntegerField()),
                ('nombre_nuites', models.IntegerField()),
                ('nombre_chambre_double', models.IntegerField()),
                ('nombre_chambre_single', models.IntegerField()),
                ('type_de_vue', models.CharField(max_length=255)),
                ('formule', models.CharField(max_length=255)),
                ('montant_factures', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote_part', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annee_facturation', models.IntegerField()),
                ('mois_facturation', models.IntegerField()),
                ('statut', models.CharField(max_length=255)),
                ('date_correspondant_statut', models.DateField()),
                ('date_demande_voucher', models.DateField()),
                ('date_envoi_voucher', models.DateField()),
                ('nature_periode', models.CharField(max_length=255)),
                ('saison', models.CharField(max_length=255)),
                ('reference_paiement', models.CharField(max_length=255)),
                ('nbr_etoiles', models.IntegerField()),
            ],
        ),
    ]
