# Generated by Django 5.0.7 on 2024-07-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_historique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='annee_facturation',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='cat_prof',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='date_correspondant_statut',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='date_demande_voucher',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='date_envoi_voucher',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='formule',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='mois_facturation',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='montant_factures',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nature_periode',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nbr_etoiles',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nombre_accompagnateurs',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nombre_chambre_double',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nombre_chambre_single',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nombre_enfants_chambre_parents',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='nombre_total_enfants',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='quote_part',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='reference_paiement',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='saison',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='total_membres_famille',
        ),
    ]
