# Generated by Django 5.0.7 on 2024-08-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_agent_demande_vue_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_debut_retraite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
