# Generated by Django 5.0.7 on 2024-08-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_demande_agence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vue',
        ),
    ]
