# Generated by Django 5.0.7 on 2024-08-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_delete_vue'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='nature_periode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='statut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
