# Generated by Django 5.0.7 on 2024-08-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_demande_nature_periode_demande_site_demande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='numero_demande',
            field=models.CharField(default='DEFAULT_VALUE', max_length=255),
        ),
    ]
