# Generated by Django 5.0.7 on 2024-08-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_demande_numero_demande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejecteddemandesretrait',
            options={},
        ),
        migrations.AlterField(
            model_name='rejecteddemandesretrait',
            name='matricule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejecteddemandesretrait',
            name='nom_agent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejecteddemandesretrait',
            name='numero_demande',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejecteddemandesretrait',
            name='prenom_agent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejecteddemandesretrait',
            name='type_de_vue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejecteddemandesretrait',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
