# Generated by Django 5.0.7 on 2024-08-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_rejecteddemandesretrait_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='DemandesTraiter',
        ),
        migrations.DeleteModel(
            name='Historique',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
        migrations.DeleteModel(
            name='RejectedDemandesRetrait',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
