# Generated by Django 5.0.7 on 2024-08-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlevendu',
            name='client',
        ),
    ]
