# Generated by Django 5.0.7 on 2024-08-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_articlevendu_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='travailleur',
        ),
    ]
