# Generated by Django 5.0.7 on 2024-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_vente_travailleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_admins/')),
            ],
        ),
    ]
